# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20171221_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default=django.utils.timezone.now, max_length=48),
            preserve_default=False,
        ),
    ]
